### ISSUE TITLE
Mention animation advantage for react-native/StatusBar

### ISSUE THREAD

**Issue by Noitidart** [Jazmon/react-native-onscreen-navbar#11]
`StausBar.setBackgroundColor` - http://facebook.github.io/react-native/docs/statusbar.html#setbackgroundcolor - has a disadvantage in comparison to this module - the animation is like a sliding animation within the status bar. Your module offers the fade in fade out animation which is what I was looking for. Is this just by accident? Or is it possible to pick animation types in Android status bar changes?

Is it also possible to control just statusbar color? Or just softbar color?

**Comment by attehuhtakangas** [comment]
[I use mostly same kind of code](https://github.com/jazmon/react-native-onscreen-navbar/blob/master/android/src/main/java/com/attehuhtakangas/navigationbar/NavigationBarModule.java#L71) as the [StatusBar implementation uses](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/statusbar/StatusBarModule.java#L86). 

Beyond that I have no idea as I tried to do it the same way as the StatusBar. If you are interested, Google around and look in the Android documentation what is possible. If it is possible, you can make a PR and i'll gladly look into it.
