### ISSUE TITLE
isTranslucent method

### ISSUE THREAD

**Issue by Noitidart** [Jazmon/react-native-onscreen-navbar#12]
May I please reuqest a `isTranslucent` method? Because i needed to detect if status bar is going to overlap or not. And there is a bug in RN implemtnation that is not being fixed:

https://github.com/facebook/react-native/issues/16432#issuecomment-345419116

```
import { StatusBar } from 'react-native'

console.log('StatusBar.translucent:', StatusBar.translucent); // should be false - is undefined
StatusBar.setTranslucent(true);
console.log('StatusBar.translucent:', StatusBar.translucent); // should be true - is undefined
```

**Comment by attehuhtakangas** [comment]
'isTranslucent' method or a variable for StatusBar isn't what this library is for. Really sucks that it doesn't work for you currently in the base React Native library, but that's where it should be fixed. 

--- 

I didn't get the same impression as you might have gotten from the issue you just posted that they wouldn't fix it. [Here's the code for StatusBar in RN](https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js#L256) it seems like it should work to me. I think you are understanding wrong how it works. You are setting the translucent prop to the StatusBar, thus "overriding" the behavior. It's up to you to store the isTranslucent-boolean somewhere, like in the component's state or some state management library of your choice.

Minimal example:
```javascript
import { StatusBar, View } from 'react-native';
import React from 'react';

class MyApp extends React.Component {
  constructor(props) {
    this.state = {
      translucentStatusBar: true,
    }
  }

  render() {
    return (
      <View>
        <StatusBar translucent={this.state.translucentStatusBar} />
      </View>
    );
  }
}
```

**Comment by Noitidart** [comment]
Oh thanks @jazmon so it always starts up in non-translucent mode huh? And then whenever I change it I can just keep track?

Really appreciate the help here!

**Comment by attehuhtakangas** [comment]
By default it's not translucent, unless you give it the prop to tell it to be transulcent

**Comment by Noitidart** [comment]
Thanks very much!
