### ISSUE TITLE
backgroundColor not working (Android)

### ISSUE THREAD

**Issue by mjmasn** [Jazmon/react-native-onscreen-navbar#16]
Hey @jazmon, I have a couple of questions about this package...

With a backgroundColor set, the top status bar's color is changed (which has me confused as to why the examples also include `<StatusBar>` from 'react-native'), but the bottom navigation bar always remains black. If I set transparent attribute then the color is always translucent black. Is there any way to set the colour to exactly match the background of the view? I'm using a Nexus 5X if that makes any difference.

I can't get the example repo to run either - firstly the `file://../..` url in `package.json` obviously doesn't work unless you place a copy of the package in that location. Then `yarn start` gives a SyntaxError which looks like something isn't handling the es6 syntax properly. Any pointers would be appreciated :)

```
SyntaxError: react-native-onscreen-navbar-example/node_modules/react-native/packager/src/Bundler/index.js: Unexpected token, expected , (47:26)
  45 |   mainModuleName: string,
  46 |   options: {},
> 47 |   getDependencies: string => Promise<Array<string>>,
     |                           ^
  48 | ) => {} | Promise<{}>;
  49 | 
  50 | const sizeOf = denodeify(imageSize);
```

**Comment by attehuhtakangas** [comment]
The example uses `StatusBar` just to show how it is similar.

Ahh yes good point on the example repo, the dependency should really just import the package itself from npm. (The example used to be in the same repo but i moved it away)

We also made a breaking change at 2.0.0 so it might break the example.

I'll try to fiddle around with the example repo and make it work with 2.0.0

**Comment by mjmasn** [comment]
@jazmon thanks for the quick reply :)

**Comment by attehuhtakangas** [comment]
@mjmasn [the example project](https://github.com/jazmon/react-native-onscreen-navbar-example) works now, give it a go :)

**Comment by attehuhtakangas** [comment]
@mjmasn did you manage to get it work?

**Comment by mjmasn** [comment]
Hey @jazmon, designs ended up changing so we didn't make use of this in the end. Thanks for looking into it though, hope I didn't waste your time.

**Comment by attehuhtakangas** [comment]
Ok, no worries! :) The example repo was outdated anyways so it really was due to some updating.

I'll close the issue since I think it should work, at least in the example repo.
